import { createKeywordsGranular, createSimpleKeyWordsGranular } from "./keyword";

var tempdata = [
    "Film / Movie Theatre",
    "Digital Filmmaking",
    "Film and Newspaper / Journal",
    "Montage/Editing",
    "Dialogue",
    "Japanese Colonial Period, 1895-1945",
    "Animated Films",
    "Taiwanese-dialect Film, 1955-1982",
    "Central Motion Picture Corporation (Zhong Yang Dian Ying Shi Ye Gu Fen You Xian Gong Si / Zhong ying), 1954-",
    "Ximending (Ximenting), 1896-",
    "Film Producers, Directors, Actors, Actresses, cinematographers, Critics, scholars, Song / music composers, and ScreenWriters (Including biographies and autobiographies)",
    "China Motion Picture Studio (Zhongguo Dian Ying Zhi Pian Chang / Zhong zhi), 1933-",
    "Interdisciplinary Studies",
    "Taiwan New Cinema",
    "Union Film Co., Ltd. (Lian Bang Ying Ye You Xian Gong Si / Lian bang), 1953-1980",
    "Individual Actors and Actresses",
    "Film Movements and Theory",
    "Film and Politics",
    "Mandarin Film, 1963-1970",
    "Films in Taiwan and Korea",
    "Movie Cameras, Projectors, and Related Equipment",
    "Film Grammar",
    "Film and Religion",
    "Film Technology",
    "Film and Sexuality / Homosexuality",
    "Dictionaries",
    "Film and Youth",
    "Film and Management",
    "Film and Sociology (Area/Audience/City/Culture/Society)",
    "Tiensheng & Tienhua Film Company (Tian Sheng, Tian Hua Ying Ye Gong Si), 1960-1978",
    "Ethnographic Films",
    "Film HISTORY",
    "Film and Women",
    "Encyclopedias",
    "Directing",
    "Individual Cinematographers",
    "Commercial films and MTVs",
    "Film and Hakka",
    "Subsidy",
    "Teenage-Campus Films",
    "Independent Films",
    "Taiwan International Ethnographic Film Festival, 2001-",
    "Taiwan International Documentary Festival, 1998-",
    "Golden Horse Film Festival and Awards, 1962-",
    "Ten Worst Films Incident, 1977",
    "SPECIFIC FILM GENRES",
    "Taichung (Taizhong or T’ai-chung), 1910-",
    "Historiophoty",
    "Film Festivals and Awards",
    "Directories",
    "Qiongyao’s/Melodrama Films",
    "Film and Videotape",
    "Film stories, Screenplays, AND SCRIPTS",
    "Musical Films",
    "Individual Music/Song Composers and Song Lyric Writers",
    "Independent Film-Making",
    "Film and Literature",
    "Film and Law",
    "Film and Technology",
    "Anti-Communist Films",
    "Literary Films",
    "Film Distribution",
    "Bibliographies and Filmographies",
    "Film and Education",
    "Contemporary Taiwan Film, 1980-",
    "Others",
    "Taiwan Provincial Film Production Studio (Taiwan sheng Dian Ying She Zhi Chang / Taiwan Sheng Zheng Fu Xin Wen Dian Ying Zhi Pian Chang / Taiwan Dian Ying Zhi Pian Chang / Taiwan Dian Ying Wen Hua Shi Ye Gu Fen You Xian Gong Si / Tai ying or Tai zhi), 1945-1999",
    "Women Make Waves Film Festival, 1993-",
    "Film and Animal",
    "Film and Archive",
    "2.28 Incident, 1947",
    "Opera / Drama Films",
    "Film THEORY AND TECHNIQUE",
    "Film and Television, Internet, Multimedia",
    "Digitalization, Preservation, and Restoration",
    "Film and Medicine / Mental Illness",
    "Taiwan Film & Culture Association (Taiwan Dian Ying Wen Hua Xie Hui), 2001-",
    "Film and Colonialism",
    "Cultural Criticism",
    "Movie Sound Recording",
    "General:",
    "Film Artifacts",
    "Golden Harvest Awards for Outstanding Short Films, 1978-",
    "Grand Motion Pictures Co., Ltd. (Guo Lian Dian Ying Gong Si / Guo lian), 1963-1967",
    "Special Effects",
    "Taipei Film Festival and Awards, 1998-",
    "Film Education",
    "Keelung (Jilong or Chi-lung), 1908-",
    "Film and Psychology",
    "Film Review",
    "Hsinchu (Xinzhu), 1900-",
    "Children’s Films",
    "Critics and Scholars",
    "Producers / Policy Makers; Chapter 4 assesses interview results; and Chapter 5 provides a conclusion.",
    "Film Investment",
    "Films in Taiwan and Japan",
    "Early period after Taiwan retrocession, 1945-1949",
    "Kaohsiung (Gaoxiong) and Southern Taiwan, including Pingtung (Pingdong or P’ing-tung), Tainan (T’ai-nan), and Chiayi (Jiayi or Chia-i), 1900-",
    "Film and Railway",
    "Film Industry",
    "Scenery and Set Design",
    "Film Law, Policy, Regulation, and Legal Case",
    ". Trailers",
    "Postcolonial Theory",
    "Taiwan and Hollywood Films",
    "Aesthetics",
    "Taipei (Taibei), 1950 -",
    "General",
    "Healthy Realism Film, 1963-1980",
    "Film Screen Quota",
    "Xin hua Film Corporation (Xin hua Ying Ye Gong Si), 1935-1984",
    "Asia Film Corporation (Yazhou Ying Ye Gong Si), 1952-",
    "Individual Producers and Directors",
    "Comparative Film Study",
    "Healthy Realism",
    "8.23 The Second Taiwan Strait Crisis, 1958",
    "Film Copyright, Piracy, and Intellectual Property",
    "Catalogs, Guides, Handbooks, Factfinders, and Manuals:",
    "Film Censorship",
    "Film and Patients",
    "Producers and Directors:",
    "Short Films",
    "Film Posters",
    "Film Institutions and Studios",
    "Screenplay Writing",
    "Individual Film Reviews",
    "Film Market, Marketing, and Box Office",
    "Indexes",
    "Individual Screenwriters",
    "Movie Content Management",
    "Actors and Actresses:",
    "First Motion Pictures Co., Ltd (Di Yi Ying Ye Ji Gou You Xian Gong Si), 1967-",
    "Film Still",
    "New Talents, Young Cinema Film Festival, 2004-",
    "REFERENCE MATERIALS",
    "Foreign Laborers",
    "Science and Education Films",
    "Acting",
    "Music/Song Composers and Song Lyric Writers",
    "Homosexual / Gay / Lesbian Films",
    "Horror and Ghost Films",
    "Special Regions, Periods, and Events",
    "Art Films",
    "Cinematography",
    "Music and Soundtrack Composition",
    "Film and Drama / Opera",
    "5.20 Incident, 1988 and Social Movement Documentary, 1980s-1990s",
    "Film and Ethnology",
    "Taiwan and Bollywood Films",
    "Film, Nationalism, Nationality, Identity, and Localization",
    "“A” / Restricted / Pornographic Films",
    "Chinese Taipei Film Archive (Cai Tuan Fa Ren Guo Jia Dian Ying Zi Liao Guan), 1991-",
    "Film and Anthropology",
    "Film and Music / Song",
    "Film Music and Song",
    "Film and Aboriginal People",
    "Comedy Films",
    "Taiwan International Animation Festival, 2003-",
    "Martial Arts / Kung Fu Films",
    "Film Propaganda",
    "Documentary Films",
    "Asia Pacific Film Festival, 1953-",
    "Film and Globalization",
    "Individual Critics and Scholars",
    "Screenwriters:",
    "Taiwan New, New-New, and Post-New Cinema, 1982-",
    "Film and Environmental Protection",
    "Films in Taiwan, Hong Kong, and Mainland China",
    "Cinematographers",
    "Film Subtitle",
    "Film and Mainland Chinese",
    "Film and Painting",
    "Film Production and Management",
    "Film and Economy",
  ];
export const genSubjectKeyWords = () =>{
    let subjectKeywordMap = {}
    tempdata.forEach((subject)=>{
        subjectKeywordMap[subject] = Array.from(createSimpleKeyWordsGranular(subject))
    })
    return subjectKeywordMap;
}

