export const PROD = true;
let apiURL;
if (PROD) {
  apiURL = "https://sillysillycreatures.xyz/api/";
} else {
  apiURL = "http://localhost:4000/api/";
}
export const API_URL = apiURL;

export const allLC = [
  "chi",
  "eng",
  "jpn",
  "duxiu",
  "zh-cn",
  "ja",
  "ko",
  "zh-tw",
  "fre",
  "ita",
  "per"
];
export const allSubjects = [
  "2.28 Incident, 1947",
  "5.20 Incident, 1988 and Social Movement Documentary, 1980s-1990s",
  "8.23 The Second Taiwan Strait Crisis, 1958",
  "20: 30: 40 (2004)",
  "“A”/Restricted/Ponographic Films",
  "Aboriginal People",
  "See Film and Aboriginal People",
  "Acting",
  "Actors and Actresses",
  "Aesthetics",
  "Ai de fa sheng lian xi = So Called Love (2008)",
  "愛的發聲練習 (2008)",
  "Ai qing wan sui = Vive L’amour (1994)",
  "愛情萬歲 (1994)",
  "Animal",
  "See Film and Animal",
  "An lian Taohuayuan = The Peach Blossom Land (1992)",
  "暗戀桃花源 (1992)",
  "And She Wasn’t (2000)",
  "See Mei can jia = And She Wasn’t (2000)",
  "Animated Films",
  "Anti-Communist Films",
  "Anthropology",
  "See Film and Anthropology",
  "Area",
  "See Film and Sociology (Area/Audience/Family/City/Culture/Society)",
  "Archive",
  "See Film and Archive",
  "Art Films",
  "Artifacts",
  "See Film Artifacts",
  "Asia Film Corporation (Yazhou Ying Ye Gong Si), 1952-",
  "Asia Pacific Film Festival, 1953-",
  "Audience",
  "See Film and Sociology (Area/Audience/Family/City/Culture/Society)",
  "Awards",
  "See Film Festivals and Awards",
  "Bai, Jingrui , 1931-1997",
  "白景瑞, 1931-1997",
  "Bai, Ke, 1913-1964",
  "白克, 1913-1964",
  "Bao dao da meng = Bodo (1993)",
  "寶島大夢 (1993)",
  "Bao dao man po = Formosa Mambo (2011)",
  "寶島漫波 (2011)",
  "Bei qing cheng shi = A City of Sadness (1989)",
  "悲情城市 (1989)",
  "Bibliographies and Filmographies",
  "Blue Gate Crossing (2002)",
  "See Lan se da men = Blue Gate Crossing (2002)",
  "Bodo (1993)",
  "See Bao dao da meng = Bodo (1993)",
  "A Borrowed Life (1994)",
  "See Duosang  = A Borrowed Life (1994)",
  "Box Office",
  "See Film Market, Marketing, and Box Office",
  "A Brighter Summer Day (1991)",
  "See Guling jie shao nian sha ren shi jian = A Brighter Summer Day (1991)",
  "Brokeback Mountain (2005)",
  "Bu jian = The Missing (2003)",
  "不見 (2003)",
  "Bu san = Goodbye, Dragon Inn (2003)",
  "不散 (2003)",
  "Cafe Lumiere (2003)",
  "See Ka fei shi guang = Cafe Lumiere (2003)",
  "Cai, Guoxian",
  "蔡國顯.",
  "Cai, Mingliang (Tsai, Ming-liang), 1957-",
  "蔡明亮, 1957-",
  "Cai Tuan Fa Ren Guo Jia Dian Ying Zi Liao Guan",
  "See Chinese Taipei Film Archive (Cai Tuan Fa Ren Guo Jia Dian Ying Zi Liao Guan), 1991-",
  "Camera",
  "See Movie Camera, Projector, and Related Equipment",
  "Campus Films",
  "See Teenage-Campus Films",
  "Cao, Jian, 1922-2002",
  "曹健, 1922-2002",
  "Cape No. 7 (2008)",
  "See Haijiao qi hao = Cape No. 7 (2008)",
  "Catch (2006)",
  "See Guo shi wu shuang = Catch (2006)",
  "Catalogs, Guides, Handbooks, Factfinders, and Manuals\t\t\t\t\t0049-0069",
  "Censorship",
  "See Film Censorship",
  "Central Motion Picture Corporation (Zhong Yang Dian Ying Shi Ye Gu Fen You Xian Gong Si / Zhong ying), 1954-",
  "Chang, Cheh",
  "See Zhang, Che (Chang, Cheh), 1923-2002.",
  "Chang, Tso-chi",
  "See Zhang, Zuoji (Chang, Tso-chi), 1961-",
  "Chang, Yi",
  "See Zhang, Yi (Chang, Yi), 1951-",
  "Cheng, Wun-hui",
  "See Zheng, Wenhui (Cheng, Wun-hui), 1981-2007",
  "Chiayi (Chia-i)",
  "See Kaohsiung (Gaoxiong) and Southern Taiwan, including Pingtung (Pingdong or P’ing-tung), Tainan (T’ai-nan), and Chiayi (Jiayi or Chia-i), 1900-",
  "Chi-lung",
  "See Keelung (Jilong or Chi-lung), 1908-",
  "China Motion Picture Studio (Zhongguo Dian Ying Zhi Pian Chang /Zhong zhi), 1933-",
  "Chinese Taipei Film Archive (Cai Tuan Fa Ren Guo Jia Dian Ying Zi Liao Guan), 1991-",
  "Children’s Films",
  "Chiu, Ming-chong",
  "See Qiu, Mingcheng (Chiu, Ming-chong), 1952-",
  "Chou, Jay",
  "See Zhou, Jielun (Chou, Jay), 1979-",
  "Chou, Tien-su",
  "See Zhou, Tiansu (Chou, Tien-su), 1910-",
  "Chou, Zoru",
  "See Zhou, Meiling (Chou, Zoru), 1969-",
  "Ci Ling = The Treasure Hunter (2009) / 刺陵 (2009)",
  "Cinematographers",
  "Cinematography",
  "City",
  "See Film and Sociology (Area/Audience/Family/City/Culture/Society)",
  "A City of Sadness (1989)",
  "See Bei qing cheng shi = A City of Sadness (1989)",
  "Colonialism",
  "See Film and Colonialism",
  "Comedy Films",
  "Commercial Films and MTVs",
  "Comparative Film Study",
  "Contemporary Taiwan Film, 1980-",
  "Copyright",
  "See Film Copyright, Piracy, and Intellectual Property",
  "Critics and Scholars",
  "Crouching Tiger, Hidden Dragon (2000)",
  "See Wo hu cang long = Crouching Tiger, Hidden Dragon (2000)",
  "Culture",
  "See Film and Sociology (Area/Audience/Family/City/Culture/Society)",
  "Cultural Criticism",
  "Dai shu nan ren = Kangaroo Man (1994)",
  "袋鼠男人 (1994)",
  "Dan dao shuang bu da = Every Odd Numbered Day (1994)",
  "單打雙不打 (1994)",
  "Dan, Hanzhang (Tan, Fred), 1949-1990",
  "但漢章, 1949-1990",
  "Di Yi Ying Ye Ji Gou You Xian Gong Si",
  "See First Motion Pictures Co., Ltd (Di Yi Ying Ye Ji Gou You Xian Gong Si), 1967-",
  "Dialogue",
  "Dictionaries",
  "Digital Filmmaking",
  "Digitization, Preservation, and Restoration",
  "Ding, Boshen, 1916-",
  "丁伯駪, 1916-",
  "Directing",
  "Directories",
  "Distribution",
  "See Film Distribution",
  "Documentary Films",
  "Dong = The Hole (1998) / 洞 (1998)",
  "Double vision (2002)",
  "See Shuang tong = Double vision (2002)",
  "Doubles / Giddens (2009)",
  "See San sheng you xing = Doubles / Giddens (2009)",
  "Doyle, Christopher (Du, Kefeng), 1952-",
  "杜可風, 1952-",
  "Drama",
  "See Film and Drama/Opera",
  "Drama Films",
  "See Opera/Drama Films",
  "Drop me a cat (2002)",
  "See Gei wo yi zhi mao = Drop me a cat (2002)",
  "Du, Kefeng",
  "See Doyle, Christopher (Du, Kefeng), 1952-",
  "Duosang  = A Borrowed Life (1994)",
  "多桑 （1994）",
  "Dust in the Wind (1986)",
  "See Lian lian feng chen = Dust in the Wind (1986)",
  "Early Period after Taiwan Retrocession, 1945- 1949",
  "Economy",
  "See Film and Economy",
  "Editing",
  "See Montage/Editing",
  "Education",
  "See Film and Education",
  "Education Films",
  "See Science and Education Films",
  "Encyclopedias",
  "Environmental Protection",
  "See Film and Environmental Protection",
  "Ethnographic Films",
  "Ethnology",
  "See Film and Ethnology",
  "The Everlasting Glory (1974)",
  "See Ying lie qian qiu = The Everlasting Glory (1974)",
  "Every Odd Numbered Day (1994)",
  "See Dan dao shuang bu da = Every Odd Numbered Day (1994)",
  "Everything For the Events of Tomorrow (1988)",
  "See Yi qie wei le ming tian = Everything For the Events of Tomorrow (1988)",
  "Execution in Autumn (1972)",
  "See Qiu jue = Execution in Autumn (1972)",
  "Face (2009)",
  "See Lian = Face (2009)",
  "Factfinders",
  "See Catalogs, Guides, Handbooks, Factfinders, and Manuals",
  "Fall …… in Love (2004)",
  "See Lian ren = Fall …… in Love (2004)",
  "Family",
  "See Film and Sociology (Area/Audience/Family/City/Culture/Society)",
  "Festivals",
  "See Film Festivals and Awards",
  "Film and Aboriginal People",
  "Film and Animal",
  "Film and Anthropology",
  "Film and Archive",
  "Film and Colonialism",
  "Film and Drama/Opera",
  "Film and Economy",
  "Film and Education",
  "Film and Environmental Protection",
  "Film and Ethnology",
  "Film and Globalization",
  "Film and Hakka",
  "Film and Law",
  "Film and Literature",
  "Film and Mainlanders",
  "Film and Management",
  "Film and Medicine/Mental Illness",
  "Film and Music/Song",
  "Film, Nationalism, Nationality, Identity, and Localization",
  "Film and Newspaper/Journal",
  "Film and Painting",
  "Film and Patients",
  "Film and Politics",
  "Film and Psychology",
  "Film and Railway",
  "Film and Religion",
  "Film and Sexuality / Homosexuality",
  "Film and Sociology (Area/Audience/Family/City/Culture/Society)",
  "Film and Technology",
  "Film and Television, Internet, Multimedia",
  "Film and Videotape",
  "Film and Women",
  "Film and Youth",
  "Film Artifacts",
  "Film Censorship",
  "Film Copyright, Piracy, and Intellectual Property",
  "Film Distribution",
  "Film Education",
  "Film Festivals and Awards",
  "Film Grammar",
  "Film history",
  "General",
  "Special Regions, Periods, and Events",
  "Ximending (Ximenting), 1896-",
  "Hsinchu (Xinzhu), 1900-",
  "Keelung (Jilong or Chi-lung), 1908-",
  "Kaohsiung (Gaoxiong) and Southern Taiwan, including",
  "Pingtung (Pingdong or P’ing-tung), Tainan (T’ai-nan), and",
  "Chiayi (Jiayi or Chia-i),1900-",
  "Taichung (Taizhong or T’ai-chung), 1910-",
  "Taipei (Taibei), 1950-",
  "Japanese Colonial Period, 1895-1945",
  "Early Period after Taiwan Retrocession, 1945- 1949",
  "Taiwanese-dialect Film, 1955-1982",
  "Mandarin Film, 1963-1970",
  "Healthy Realism Film, 1963-1980",
  "Contemporary Taiwan Film, 1980-",
  "Taiwan New, New-New, and Post-New Cinema, 1982-",
  "2.28 Incident, 1947",
  "8.23 The Second Taiwan Strait Crisis, 1958",
  "Ten Worst Films Incident, 1977",
  "5.20 Incident, 1988 and Social Movement Documentary,",
  "Film Institutions and Studios",
  "China Motion Picture Studio (Zhongguo Dian Ying Zhi Pian",
  "Chang /Zhong zhi), 1933-",
  "Xinhua Film Corporation (Xinhua Ying Ye Gong Si), 1935-1984",
  "Taiwan Provincial Film Production Studio (Taiwan sheng Dian Ying",
  "She Zhi Chang / Taiwan Sheng Zheng Fu Xin Wen Dian Ying Zhi Pian",
  "Chang / Taiwan Dian Ying Zhi Pian Chang / Taiwan Dian Ying Wen Hua",
  "Shi Ye Gu Fen You Xian Gong Si  / Tai ying or Tai zhi), 1945-1999",
  "Asia Film Corporation (Yazhou Ying Ye Gong Si), 1952-",
  "Union Film Co., Ltd. (Lian Bang Ying Ye You Xian Gong Si / Lian bang), 1953-1980",
  "Central Motion Picture Corporation (Zhong Yang Dian Ying Shi Ye Gu Fen You Xian Gong Si / Zhong ying), 1954-",
  "Tiensheng & Tienhua Film Company (Tian Sheng, Tian Hua Ying Ye Gong Si), 1960-1978",
  "Grand Motion Pictures Co., Ltd. (Guo Lian Dian Ying Gong Si / Guo lian), 1963-1967",
  "First Motion Pictures Co., Ltd (Di Yi Ying Ye Ji Gou You Xian Gong Si),",
  "Chinese Taipei Film Archive (Cai Tuan Fa Ren Guo Jia Dian Ying Zi Liao Guan), 1991-",
  "Taiwan Film & Culture Association (Taiwan Dian Ying Wen Hua Xie",
  "Hui),  2001-",
  "Film Industry",
  "Film Investment",
  "Film Law, Policy, Regulation, and Legal Case",
  "Film/Movie Theatre",
  "Film Music and Song",
  "Film Posters",
  "Film Production and Management",
  "Film Still",
  "Film Subsidy",
  "Film Subtitle",
  "Films in Taiwan and Japan",
  "Films in Taiwan and Korea",
  "Films in Taiwan, Hong Kong, and Mainland China",
  "Film Institutions and Studios",
  "Film Market, Marketing, and Box Office",
  "Film Movements and Theory",
  "Film Producers, Directors, Actors, Actresses, CINEMATOGRAPHERS, Critics, scholars, music/ song composers amd song lyric writers, ScreenWriters (Includes biographies and autobiographies)",
  "General",
  "Producers and Directors",
  "General",
  "Individual Producers and Directors",
  "Bai, Jingrui , 1931-1997",
  "白景瑞, 1931-1997",
  "Bai, Ke, 1913-1964",
  "白克, 1913-1964",
  "Cai, Guoxian",
  "蔡國顯.",
  "Cai, Mingliang (Tsai, Ming-liang), 1957-",
  "蔡明亮, 1957-",
  "Dan, Hanzhang, 1949-1990",
  "但漢章, 1949-1990",
  "Ding, Boshen, 1916-",
  "丁伯駪, 1916-",
  "Gong, Hong, 1915-2004",
  "龔弘, 1915-2004",
  "Guo, Nanhong (Kuo, Joseph), 1933-",
  "郭南宏 (Kuo, Joseph), 1933-",
  "He, Feiguang, 1913-1997",
  "何非光, 1913-1997",
  "Hou, Xiaoxian (Hou, Hsiao-hsien), 1947-",
  "侯孝賢, 1947-",
  "Hu, Jinquan (Hu, King), 1932-1997",
  "胡金銓, 1932-1997",
  "Huang, Zhuohan (Huang, Cho-han), 1920-",
  "黃卓漢, 1920-",
  "Jiubadao (Ke, Jingteng  and Ko, Giddens), 1978-",
  "九把刀 (柯景騰), 1978-",
  "Ke, Shuqing.",
  "柯淑卿.",
  "Lai, Shengchuan (Lai, Stan), 1954-",
  "賴聲川, 1954-",
  "Lan, Tianhong, 1924-2007",
  "藍天虹, 1924-2007",
  "Li, An (Lee, Ang), 1954-",
  "李安, 1954-",
  "Li, Ding.",
  "李鼎.",
  "Li, Gang, 1957-",
  "李崗, 1957-",
  "Li, Hanxiang (Li, Han-hsiang), 1926-1996",
  "李翰祥, 1926-1996",
  "Li, Kangsheng (Lee, Kang-sheng), 1968-",
  "李康生, 1968-",
  "Li, Xing, 1930-",
  "李行, 1930-",
  "Liang, Xiushen (Liang, Slim), 1948-",
  "梁修身, 1948-",
  "Liao, Xiangxiong, 1933-",
  "廖祥雄, 1933-",
  "Lin, Tuanqiu, 1920-1998",
  "林摶秋, 1920-1998",
  "Lin, Zhengsheng, 1959-",
  "林正盛, 1959-",
  "Liu, Na’ou, 1905-1940",
  "劉吶鷗, 1905-1940",
  "Long, Fang, 1915-1964",
  "龍芳, 1915-1964",
  "Lu, Sushang, 1915-1970.",
  "呂訴上, 1915-1970.",
  "Luo, Xuelian, 1902-2000",
  "羅學濂, 1902-2000",
  "Ming, Ji, 1939-",
  "明驥, 1939-",
  "Ou, Wei, 1937-1973",
  "歐威, 1937-1973",
  "Qiu, Mingcheng (Chiu, Ming-chong), 1952-",
  "邱銘誠, 1952-",
  "Sha, Rongfeng, 1921-",
  "沙榮峰, 1921-",
  "Tong, Yuejuan (Wan, Xiuying; Liang, Ruiying), 1914-",
  "童月娟 (萬秀英, 梁瑞英), 1914-",
  "Toyojiro, Takamatsu, 1872-1952",
  "高松豐次郎, 1872-1952",
  "Wang, Feilin, 1956-1992.",
  "王菲林, 1956-1992.",
  "Wang, Shengshan, 1921-2003",
  "王生善, 1921-2003",
  "Wang, Tong (Wang, Tung) 1942-",
  "王童, 1942-",
  "Wang, Xiaodi, 1953-",
  "王小棣, 1953-",
  "Wang, Tong (Wang, Tung) 1942-",
  "王童, 1942-",
  "Wang, Zhengfang.",
  "王正方.",
  "Wei, Desheng (Wei, Te-sheng), 1969-",
  "魏德聖, 1969-",
  "Weng, Dacheng, 1944-",
  "翁大成, 1944-",
  "Wu, Misen (Wu, Mi-sen) 1967-",
  "吳米森, 1967-",
  "Wu, Nianzhen (Wu, Nien-chen), 1952-",
  "吳念真1952-",
  "Xiao, Juzhen (Hsiao, Chu-chen), 1972-",
  "蕭菊貞, 1972-",
  "Xin, Qi (Hsin, Chi), 1924-",
  "辛奇, 1924-",
  "Xu, Ligong (Hsu, Li-kong).",
  "徐立功.",
  "Yang, Dechang (Yang, Edward), 1947-2007",
  "楊德昌, 1947-2007",
  "Yao, Fengpan (Yao, Feng-pan), 1932-2004",
  "姚鳳磐, 1932-2004",
  "Yi, Wen (Yang, Evan), 1920-1978",
  "易文, 1920-1978",
  "Yuan, Congmei (Yuan, Tsung-mei), 1905-",
  "袁叢美, 1905-",
  "Zhang, Che (Chang, Cheh), 1923-2002.",
  "張徹, 1923-2002.",
  "Zhang, Yi (Chang, Yi), 1951-",
  "張毅, 1951-",
  "Zhang, Ying, 1913-",
  "張英, 1913-",
  "Zhang, Zengze, 1930-",
  "張曾澤, 1930-",
  "Zhang, Zuoji (Chang, Tso-chi), 1961-",
  "張作驥, 1961-",
  "Zheng, Wenhui (Cheng, Wun-hui), 1981-2007",
  "鄭文惠, 1981-2007",
  "Zhou, Meiling (Chou, Zoru), 1969-",
  "周美玲, 1969-",
  "Zhou, Tiansu (Chou, Tien-su), 1910-",
  "周天素, 1910-",
  "Actors and Actresses",
  "General",
  "Individual Actors and Actresses",
  "Cao, Jian, 1922-2002",
  "曹健, 1922-2002",
  "Gong, Jianong, 1902-1993",
  "龔稼農，1902-1993",
  "Gu, Minglun, 1948-1978",
  "谷名倫, 1948-1978",
  "Hong, Mingxue, 1940-",
  "洪明雪, 1942-",
  "Hu, Die, 1907-1989",
  "胡蝶, 1907-1989",
  "Jiang, Qing, 1946-",
  "江青, 1046-",
  "Lan, Tianhong, 1924-2007",
  "藍天虹, 1924-2007",
  "Li, Kangsheng (Lee, Kang-sheng), 1968-",
  "李康生, 1968-",
  "Li, Ying, 1923-2005",
  "李影, 1923-2005",
  "Liang, Xiushen (Liang, Slim), 1948-",
  "梁修身, 1948-",
  "Lin, Qingxia (Lin, Brigitte Ching Hsia), 1954-",
  "林青霞, 1954-",
  "Ou, Wei, 1937-1973",
  "歐威, 1937-1973",
  "Tang, Baoyun, 1944-1999",
  "唐寶雲, 1944-1999",
  "Wei, Ping’ao, 1929-1989",
  "魏平澳, 1929-1989",
  "Yang, Huishan, 1952-",
  "楊惠珊, 1952-",
  "Yang, Lihua, 1944-",
  "楊麗花, 1944-",
  "Xu, Buliao (Pu-liao Hsu), 1951-1985",
  "許不了, 1951-1985",
  "Zhang, Meiyao, 1941-",
  "張美瑤, 1941-",
  "Zhou, Jielun (Chou, Jay), 1979-",
  "周傑倫, 1979-",
  "Cinematographers",
  "General",
  "Individual Cinematographers",
  "Doyle, Christopher (Du, Kefeng), 1952-",
  "杜可風, 1952-",
  "Hua, Huiying, 1925-",
  "華慧英, 1925-",
  "Critics and Scholars",
  "General",
  "Individual Critics and Scholars",
  "Dan, Hanzhang (Tan, Fred), 1949-1990",
  "但漢章, 1949-1990",
  "Lu, Sushang, 1915-1970",
  "呂訴上, 1915-1970",
  "Luo, Xuelian, 1902-2000",
  "羅學濂, 1902-2000",
  "Wang, Feilin, 1956-1992",
  "王菲林, 1956-1992",
  "Yang, Shiqi",
  "楊士琪",
  "Yao, Yiwei, 1922-1997",
  "姚一葦, 1922-1997",
  "Music/Song Composers and Song Lyric Writers",
  "Individual Music/Song Composers and Song Lyric Writers",
  "Li, Linqiu, 1909-1979",
  "李臨秋, 1909-1979",
  "Yi, Wen (Yang, Evan), 1920-1978",
  "易文, 1920-1978",
  "Zeng, Zhongying, 1924-",
  "曾仲影, 1924-",
  "Zhang, Hongyi, 1950-2006",
  "張弘毅, 1950-2006",
  "Screenwriters",
  "Individual Screenplay Writers",
  "Gong, Min, 1931-",
  "貢敏, 1931-",
  "Li, Gang, 1957-",
  "李崗, 1957-",
  "Li, Linqiu, 1909-1979",
  "李臨秋, 1909-1979",
  "Lin, Tuanqiu, 1920-1998",
  "林摶秋, 1920-1998",
  "Lu, Sushang, 1915-1970",
  "呂訴上, 1915-1970",
  "Ma, Sen, 1932-",
  "馬森, 1932-",
  "Wang, Shengshan, 1921-2003",
  "王生善, 1921-2003",
  "Xiaoye, 1951-",
  "小野, 1951-",
  "Yao, Yiwei, 1922-1997",
  "姚一葦, 1922-1997",
  "Yi, Wen (Yang, Evan), 1920-1978",
  "易文, 1920-1978",
  "Zhang, Mingyu",
  "張明玉",
  "Zhao, Qibin, 1929-1986",
  "趙琦彬, 1929-1986",
  "Zhu, Tianwen (Chu, T’ien-wen) , 1956-",
  "朱天文, 1956-",
  "Film Propaganda",
  "Film reviews",
  "General",
  "Individual Film Reviews",
  "20: 30: 40 (2004)",
  "Ai de fa sheng lian xi = So Called Love (2008)",
  "愛的發聲練習 (2008)",
  "Ai qing wan sui = Vive L’amour (1994)",
  "愛情萬歲 (1994)",
  "An lian Taohuayuan = The Peach Blossom Land (1992)",
  "暗戀桃花源 (1992)",
  "Bao dao da meng = Bodo (1993)",
  "寶島大夢 (1993)",
  "Bao dao man po = Formosa Mambo (2011)",
  "寶島漫波 (2011)",
  "Bei qing cheng shi = A City of Sadness (1989)",
  "悲情城市 (1989)",
  "Brokeback Mountain (2005)",
  "Bu jian = The Missing (2003)",
  "不見 (2003)",
  "Bu san = Goodbye, Dragon Inn (2003)",
  "不散 (2003)",
  "Ci Ling = The Treasure Hunter (2009)",
  "刺陵 (2009)",
  "Dai shu nan ren = Kangaroo Man (1994)",
  "袋鼠男人 (1994)",
  "Dan dao shuang bu da = Every Odd Numbered Day (1994)",
  "單打雙不打 (1994)",
  "Dong = The Hole (1998)",
  "洞 (1998)",
  "Duosang  = A Borrowed Life (1994)",
  "多桑（1994）",
  "Gei wo yi zhi mao = Drop me a cat (2002)",
  "給我一支貓 (2002)",
  "Gong fu guan lan = Kung Fu Dunk (2008)",
  "功夫灌籃 (2008)",
  "Grandpa? (2009)",
  "Guling jie shao nian sha ren shi jian = A Brighter Summer Day (1991)",
  "牯嶺街少年殺人事件 (1991)",
  "Guo shi wu shuang = Catch (2006)",
  "國士無雙 (2006)",
  "Haijiao qi hao = Cape No. 7 (2008)",
  "海角七號 (2008)",
  "Hai shang hua = Flowers of Shanghai (1998)",
  "海上花 (1998)",
  "Hao nan hao nu = Good Men, Good Women (1993)",
  "好男好女（1993）",
  "He liu = The River (1997)",
  "河流 (1997)",
  "Hong qi qiu de lu xing = Flight of the Red Balloon = Le Voyage du Ballon Rouge (2006)",
  "紅氣球的旅行 (2006)",
  "Ji mo fang xin ju le bu = Lonely Hearts Club (1995)",
  "寂寞芳心俱樂部 (1995)",
  "Ka fei shi guang = Cafe Lumiere (2003)",
  "咖啡時光 (2003)",
  "Kong bu fen zi = Terrorizers (1986)",
  "恐怖份子 (1986)",
  "Lan se da men = Blue Gate Crossing (2002)",
  "藍色大門 (2002)",
  "Lian = Face (2009)",
  "臉 (2009)",
  "Lian lian feng chen = Dust in the Wind (1986)",
  "戀戀風塵 (1986)",
  "Lian lian wu = Step By Step (2009)",
  "練戀舞 (2009)",
  "Lian ren = Fall …… in Love (2004)",
  "戀人 (2004)",
  "Lian xi qu = Island Etude (2007)",
  "練習曲 (2007)",
  "Liu li dao ying = Floating Islands (2000)",
  "流離島影 (2000)",
  "Lu gang qing shen = Wind Within (1999)",
  "鹿港情深 (1999)",
  "Mei can jia = And She Wasn’t (2000)",
  "沒參加 (2000)",
  "Mengjia = Monga (2010)",
  "艋舺 (2010)",
  "Mo fa a ma = Grandma and Her Ghosts (1998)",
  "魔法阿媽 (1998)",
  "Nan fang ji shi zhi fu shi guang ying = The Strait Story (2005)",
  "南方記事之浮世光影 (2005)",
  "Ni na bian ji dian = What Time Is It There? (2001)",
  "你那邊幾點? (2001)",
  "Po lun tai = Flat Tire (1998)",
  "破輪胎 (1998)",
  "Qi mao qiu le = Fluffy Rhapsody (2000)",
  "起毛球了 (2000)",
  "Qian xi man bo = Millennium Mambo (2001)",
  "千禧曼波 (2001)",
  "Qiao ke li zhong ji = Chocolate Rap (2005)",
  "巧克力重擊 (2005)",
  "Qing shao nian Nezha = Rebels of the Neon God (1992)",
  "青少年哪吒 (1992)",
  "Qiu jue = Execution in Autumn (1972)",
  "秋決 (1972)",
  "Ren yu Duoduo = The Shoe Fairy (2006)",
  "人魚朵朵 (2006)",
  "Saideke - Balai = Seediq  Bale (2011)",
  "賽德克 – 巴萊 (2011)",
  "San sheng you xing = Doubles / Giddens (2009)",
  "三生有幸 (2009)",
  "Se Jie = Lust, Caution (2007)",
  "色,戒 (2007)",
  "Shuang tong = Double vision (2002)",
  "雙瞳 (2002)",
  "Taiwan hei dian ying = Taiwan black movies (2005)",
  "台灣黑電影 (2005)",
  "Tang shan guo Taiwan = The Heroic Pioneers (1986)",
  "唐山過台灣 (1986)",
  "Tui shou = Pushing Hands (1991)",
  "推手 (1991)",
  "Wang Xiang = Homesick Eyes (1997)",
  "望鄉 (1997)",
  "Wo de mei li yu ai chou = The Peony Pavilion (1995)",
  "我的美麗與哀愁 (1995)",
  "Wo de yi piao xuan zong tong = The Tofu Maker Had a Dream (1994)",
  "我的一票選總統 (1994)",
  "Wo hu cang long = Crouching Tiger, Hidden Dragon (2000)",
  "臥虎藏龍 (2000)",
  "Wu yue zhi lian = Love of May (2004)",
  "五月之戀 (2004)",
  "Wu zi tian shu = The Phoenix (1978)",
  "無字天書 (1978)",
  "Xi bu lai de ren = The Man From West Island (1990)",
  "西部來的人 (1990)",
  "Xi meng ren sheng = The Puppetmaster (1995)",
  "戲夢人生 (1995)",
  "Xi yan = The wedding banquet (1993)",
  "囍宴 (2003)",
  "Xia nu = A Touch of Zen (1969)",
  "俠女 (1969)",
  "Xiang fei = Princess D (2002)",
  "想飛 (2002)",
  "Xiao zhen chun hui = Gain Sons, not Losing Daughters (1968)",
  "小鎮春回 (1968)",
  "Ya pian zhan zheng = The Opium War (1997)",
  "鴉片戰爭 (1997)",
  "Yan guang si she ge wu tuan = Splendid Floart (2004)",
  "艷光四射歌舞團 (2004)",
  "Yangzi jiang feng yun = Storm Over the Yang-Tse River (1969)",
  "揚子江風雲 (1969)",
  "Yi ba jiu wu = The Legend of Formosa in 1895 (2008)",
  "一八九五 (2008)",
  "Yi qie wei le ming tian = Everything For the Events of Tomorrow (1988)",
  "一切為了明天 (1988)",
  "Yin shi nan nu = Eat Drink Man Woman (1994)",
  "飲食男女 (1994)",
  "Ying lie qian qiu = The Everlasting Glory (1974)",
  "英烈千秋 (1974)",
  "Zui hao shi guang = Three Times (2005)",
  "最好時光 (2005)",
  "Film Screen Quota",
  "film stories, Screenplays, AND SCRIPTS",
  "Film Technology",
  "General",
  "Digital Filmmaking",
  "Movie Camera, Projector,  and Related",
  "Equipment",
  "Movie Content Management",
  "Movie Sound Recording",
  "Film theory and technique",
  "General",
  "Acting",
  "Aesthetics",
  "Cinematography",
  "Cultural Criticism",
  "Dialogue",
  "Directing",
  "Montage/Editing",
  "Film Grammar",
  "Film Movements and Theory",
  "Healthy Realism",
  "Taiwan New Cinema",
  "Historiography",
  "Music and Song Composition",
  "Postcolonial Theory",
  "Scenery and Set Design",
  "Screenplay Writing",
  "Special Effects",
  "Filmographies",
  "See Bibliographies and Filmographies",
  "First Motion Pictures Co., Ltd (Di Yi Ying Ye Ji Gou You Xian Gong Si),  1967-",
  "Flat Tire (1998)",
  "See Po lun tai = Flat Tire (1998)",
  "Flight of the Red Balloon = Le Voyage du Ballon Rouge (2006)",
  "See Hong qi qiu de lu xing = Flight of the Red Balloon = Le Voyage du Ballon Rouge (2006)",
  "Floating Islands (2000)",
  "See Liu li dao ying = Floating Islands (2000)",
  "Flowers of Shanghai (1998)",
  "See Hai shang hua = Flowers of Shanghai (1998)",
  "Fluffy Rhapsody (2000)",
  "See Qi mao qiu le = Fluffy Rhapsody (2000)",
  "Foreign Laborers",
  "Formosa Mambo (2011)",
  "See Bao dao man po = Formosa Mambo (2011)",
  "Gay Films",
  "See Homosexual/Gay/Lesbian Films",
  "Gain Sons, not Losing Daughters (1968)",
  "See Xiao zhen chun hui = Gain Sons, not Losing Daughters (1968)",
  "Gaoxiong",
  "See Kaohsiung (Gaoxiong) and Southern Taiwan, including Pingtung (Pingdong or P’ing-tung), Tainan (T’ai-nan), and Chiayi (Jiayi or Chia-i), 1900-",
  "Gei wo yi zhi mao = Drop me a cat (2002)",
  "給我一支貓 (2002)",
  "Ghost Films",
  "See Horror and Ghost Films",
  "Globalization",
  "See Film and Globalization",
  "Golden Harvest Awards for Outstanding Short Films, 1978-",
  "Golden Horse Film Festival and Awards, 1962-",
  "Gong fu guan lan = Kung Fu Dunk (2008)",
  "功夫灌籃 (2008)",
  "Gong, Hong, 1915-2004",
  "龔弘, 1915-2004",
  "Gong, Jianong, 1902-1993",
  "龔稼農，1902-1993",
  "Gong, Min, 1931-",
  "貢敏, 1931-",
  "Good Men, Good Women (1993)",
  "See Hao nan hao nu = Good Men, Good Women (1993)",
  "Goodbye, Dragon Inn (2003)",
  "See Bu san = Goodbye, Dragon Inn (2003)",
  "Grand Motion Pictures Co., Ltd. (Guo Lian Dian Ying Gong Si / Guo lian), 1963-1967",
  "Grandpa!? (2009)",
  "Grandma and Her Ghosts (1998)",
  "See Mo fa a ma = Grandma and Her Ghosts (1998)",
  "Gu, Minglun, 1948-1978",
  "谷名倫, 1948-1978",
  "Guides",
  "See Catalogs, Guides, Handbooks, Factfinders, and Manuals",
  "Guling jie shao nian sha ren shi jian = A Brighter Summer Day (1991)",
  "牯嶺街少年殺人事件 (1991)",
  "Guo lian",
  "See Grand Motion Pictures Co., Ltd. (Guo Lian Dian Ying Gong Si / Guo lian), 1963-1967",
  "Guo Lian Dian Ying Gong Si",
  "See Grand Motion Pictures Co., Ltd. (Guo Lian Dian Ying Gong Si / Guo lian), 1963-1967",
  "Guo, Nanhong (Kuo, Joseph), 1933-",
  "郭南宏 (Kuo, Joseph), 1933-",
  "Guo shi wu shuang = Catch (2006)",
  "國士無雙 (2006)",
  "Haijiao qi hao = Cape No. 7 (2008)",
  "海角七號 (2008)",
  "Hai shang hua = Flowers of Shanghai (1998)",
  "海上花 (1998)",
  "Hakka",
  "See Film and Hakka",
  "Handbooks",
  "See Catalogs, Guides, Handbooks, Factfinders, and Manuals",
  "Hao nan hao nu = Good Men, Good Women (1993)",
  "好男好女 （1993）",
  "He, Feiguang, 1913-1997",
  "何非光, 1913-1997",
  "He liu = The River (1997)",
  "河流 (1997)",
  "Healthy Realism",
  "Healthy Realism Film, 1963-1980",
  "The Heroic Pioneers (1986)",
  "See Tang shan guo Taiwan = The Heroic Pioneers (1986)",
  "Historiography",
  "The Hole (1998)",
  "See Dong = The Hole (1998)",
  "Homesick Eyes (1997)",
  "See Wang Xiang = Homesick Eyes (1997)",
  "Homosexual/Gay/Lesbian Films",
  "Homosexuality",
  "See Film and Sexuality / Homosexuality",
  "Hong, Mingxue, 1940-",
  "洪明雪, 1942-",
  "Hong qi qiu de lu xing = Flight of the Red Balloon = Le Voyage du Ballon Rouge (2006)",
  "紅氣球的旅行 (2006)",
  "Horror and Ghost Films",
  "Hou, Hsiao-hsien",
  "See Hou, Xiaoxian (Hou, Hsiao-hsien), 1947-",
  "Hou, Xiaoxian (Hou, Hsiao-hsien), 1947-",
  "侯孝賢, 1947-",
  "Hsiao, Chu-chen",
  "See Xiao, Juzhen (Hsiao, Chu-chen), 1972-",
  "Hsin, Chi",
  "See Xin, Qi (Hsin, Chi), 1924-",
  "Hsinchu (Xinzhu), 1900-",
  "Hsu, Li-kong",
  "See Xu, Ligong (Hsu, Li-kong)",
  "Hu, Die, 1907-1989",
  "胡蝶, 1907-1989",
  "Hu, Jinquan (Hu, King), 1932-1997",
  "胡金銓, 1932-1997",
  "Hu, King",
  "See Hu, Jinquan (Hu, King), 1932-1997",
  "Hua, Huiying, 1925-",
  "華慧英, 1925-",
  "Huang, Zhuohan (Huang, Cho-han), 1920-",
  "黃卓漢, 1920-",
  "Huang, Cho-han",
  "See Huang, Zhuohan (Huang, Cho-han), 1920-",
  "Identity",
  "See Film, Nationalism, Nationality, Identity, and Localization",
  "Independent Films",
  "Indexes",
  "Individual Actors and Actresses",
  "Individual Cinematographers",
  "Individual Critics and Scholars",
  "Individual Film Reviews",
  "Individual Music/Song Composers and Song Lyric Writers",
  "Individual Producers and Directors",
  "Individual Screenplay Writers",
  "Industry",
  "See Film Industry",
  "Interdisciplinary Studies",
  "Comparative Film Study",
  "Films in Taiwan, Hong Kong, and Mainland China",
  "Films in Taiwan and Japan",
  "Films in Taiwan and Korea",
  "Taiwan and Bollywood Films",
  "Taiwan and Hollywood Films",
  "Film and Aboriginal People",
  "Film and Animal",
  "Film and Anthropology",
  "Film and Archive",
  "Film and Colonialism",
  "Film and Drama/Opera",
  "Film and Economy",
  "Film and Education",
  "Film and Environmental Protection",
  "Film and Ethnology",
  "Film and Globalization",
  "Foreign Laborers",
  "Film and Hakka",
  "Film and Law",
  "Film and Literature",
  "Film and Mainlanders",
  "Film and Management",
  "Film and Medicine/Mental Illness",
  "Film and Music/Song",
  "Film, Nationalism, Nationality, Identity, and Localization",
  "Film and Newspaper/Journal",
  "Film and Painting",
  "Film and Patients",
  "Film and Politics",
  "Film and Psychology",
  "Film and Railway",
  "Film and Religion",
  "Film and Sexuality / Homosexuality",
  "Film and Sociology (Area/Audience/Family/City/Culture/Society)",
  "Film and Technology",
  "Film and Television, Internet, Multimedia",
  "Film and Videotape",
  "Film and Women",
  "Film and Youth",
  "Intellectual Property",
  "See Film Copyright, Piracy, and Intellectual Property",
  "Internet",
  "See Film and Television, Internet, Multimedia",
  "Investment",
  "See Film Investment",
  "Island Etude (2007)",
  "See Lian xi qu = Island Etude (2007)",
  "Japanese Colonial Period, 1895-1945",
  "Ji mo fang xin ju le bu = Lonely Hearts Club (1995)",
  "寂寞芳心俱樂部 (1995)",
  "Jiang, Qing, 1946-",
  "江青, 1046-",
  "Jiayi",
  "See Kaohsiung (Gaoxiong) and Southern Taiwan, including Pingtung (Pingdong or P’ing-tung), Tainan (T’ai-nan), and Chiayi (Jiayi or Chia-i),1900-",
  "Jilong",
  "See Keelung (Jilong or Chi-lung), 1908-",
  "Jiubadao (Ke, Jingteng  and Ko, Giddens), 1978-",
  "九把刀 (柯景騰), 1978-",
  "Journal",
  "See Film and Newspaper/Journal",
  "Ka fei shi guang = Cafe Lumiere (2003)",
  "咖啡時光 (2003)",
  "Kangaroo Man (1994)",
  "See Dai shu nan ren = Kangaroo Man (1994)",
  "Kaohsiung (Gaoxiong) and Southern Taiwan, including Pingtung (Pingdong or P’ing-tung), Tainan (T’ai-nan), and Chiayi (Jiayi or Chia-i), 1900-",
  "Ke, Jingteng",
  "See Jiubadao (Ke, Jingteng  and Ko, Giddens), 1978-",
  "Ke, Shuqing",
  "柯淑卿",
  "Keelung (Jilong or Chi-lung), 1908-",
  "Ko, Giddens",
  "See Jiubadao (Ke, Jingteng  and Ko, Giddens), 1978-",
  "Kong bu fen zi = Terrorizers (1986)",
  "恐怖份子 (1986)",
  "Kung Fu Dunk (2008)",
  "See Gong fu guan lan = Kung Fu Dunk (2008)",
  "Kung Fu Films",
  "See Martial Arts/Kung Fu Films",
  "Kuo, Joseph",
  "See Guo, Nanhong (Kuo, Joseph), 1933-",
  "Lai, Shengchuan (Lai, Stan), 1954-",
  "賴聲川, 1954-",
  "Lai, Stan",
  "See Lai, Shengchuan (Lai, Stan), 1954-",
  "Lan se da men = Blue Gate Crossing (2002)",
  "藍色大門 (2002)",
  "Lan, Tianhong, 1924-2007",
  "藍天虹, 1924-2007",
  "Law",
  "See Film and Law",
  "See Film Law, Policy, Regulation, and Legal Case",
  "The Legend of Formosa in 1895 (2008)",
  "See Yi ba jiu wu = The Legend of Formosa in 1895 (2008)",
  "Lee, Ang",
  "See Li, An (Lee, Ang), 1954-",
  "Lee, Kang-sheng",
  "See Li, Kangsheng (Lee, Kang-sheng), 1968-",
  "Legal Case",
  "See Film Law, Policy, Regulation, and Legal Case",
  "Lesbian Films",
  "See Homosexual/Gay/Lesbian Films",
  "Li, An (Lee, Ang), 1954-",
  "李安, 1954-",
  "Li, Ding.",
  "李鼎.",
  "Li, Gang, 1957-",
  "李崗, 1957-",
  "Li, Han-hsiang",
  "See Li, Hanxiang (Li, Han-hsiang), 1926-1996",
  "Li, Hanxiang (Li, Han-hsiang), 1926-1996",
  "李翰祥, 1926-1996",
  "Li, Kangsheng (Lee, Kang-sheng), 1968-",
  "李康生, 1968-",
  "Li, Linqiu, 1909-1979",
  "李臨秋, 1909-1979",
  "Li, Xing, 1930-",
  "李行, 1930-",
  "Li, Ying, 1923-2005",
  "李影, 1923-2005",
  "Lian = Face (2009)",
  "臉 (2009)",
  "Lian bang",
  "See Union Film Co., Ltd. (Lian bang ying ye you xian gong si / Lian bang), 1953-1980",
  "Lian Bang Ying Ye You Xian Gong Si / Lian bang",
  "See Union Film Co., Ltd. (Lian Bang Ying Ye You Xian Gong Si / Lian bang), 1953-1980",
  "Lian lian feng chen = Dust in the Wind (1986)",
  "戀戀風塵 (1986)",
  "Lian lian wu = Step By Step (2009)",
  "練戀舞 (2009)",
  "Lian ren = Fall …… in Love (2004)",
  "戀人 (2004)",
  "Lian xi qu = Island Etude (2007)",
  "練習曲 (2007)",
  "Liang, Slim",
  "See Liang, Xiushen (Liang, Slim), 1948-",
  "Liang, Ruiying",
  "See Tong, Yuejuan (Wan, Xiuying; Liang, Ruiying), 1914-",
  "Liang, Xiushen (Liang, Slim), 1948-",
  "梁修身, 1948-",
  "Liao, Xiangxiong, 1933-",
  "廖祥雄, 1933-",
  "Lin, Brigitte Ching Hsia",
  "See Lin, Qingxia (Lin, Brigitte Ching Hsia), 1954-",
  "Lin, Qingxia (Lin, Brigitte Ching Hsia), 1954-",
  "林青霞, 1954-",
  "Lin, Tuanqiu, 1920-1998",
  "林摶秋, 1920-1998",
  "Lin, Zhengsheng, 1959-",
  "林正盛, 1959-",
  "Literature",
  "See Film and Literature",
  "Literary Films",
  "Liu li dao ying = Floating Islands (2000)",
  "流離島影 (2000)",
  "Liu, Na’ou, 1905-1940",
  "劉吶鷗, 1905-1940",
  "Localization",
  "See Film, Nationalism, Nationality, Identity, and Localization",
  "Lonely Hearts Club (1995)",
  "See Ji mo fang xin ju le bu = Lonely Hearts Club (1995)",
  "Long, Fang, 1915-1964",
  "龍芳, 1915-1964",
  "Love of May (2004)",
  "See Wu yue zhi lian = Love of May (2004)",
  "Lu gang qing shen = Wind Within (1999)",
  "鹿港情深 (1999)",
  "Lu, Sushang, 1915-1970.",
  "呂訴上, 1915-1970.",
  "Luo, Xuelian, 1902-2000",
  "羅學濂, 1902-2000",
  "Lust, Caution (2007)",
  "See Se Jie = Lust, Caution (2007)",
  "Ma, Sen, 1932-",
  "馬森, 1932-",
  "Mainlanders",
  "See Film and Mainlanders",
  "The Man From West Island (1990)",
  "See Xi bu lai de ren = The Man From West Island (1990)",
  "Management",
  "See Film and Management",
  "See Film Production and Management",
  "Mandarin Film, 1963-1970",
  "Manuals",
  "See Catalogs, Guides, Handbooks, Factfinders, and Manuals",
  "Market",
  "See Film Market, Marketing, and Box Office",
  "Marketing",
  "See Film Market, Marketing, and Box Office",
  "Martial Arts / Kung Fu Films",
  "Medicine",
  "See Film and Medicine/Mental Illness",
  "Mei can jia = And She Sasn’t (2000)",
  "沒參加 (2000)",
  "Melodrama Films",
  "See Qiongyao’s/Melodrama Films",
  "Mengjia = Monga (2010)",
  "艋舺 (2010)",
  "Mental Illness",
  "See Film and Medicine/Mental Illness",
  "Millennium Mambo (2001)",
  "See Qian xi man bo = Millennium Mambo (2001)",
  "Ming, Ji, 1939-",
  "明驥, 1939-",
  "The Missing (2003)",
  "See Bu jian = The Missing (2003)",
  "Mo fa a ma = Grandma and Her Ghosts (1998)",
  "魔法阿媽 (1998)",
  "Monga (2010)",
  "See Mengjia = Monga (2010)",
  "Montage/Editing",
  "Movie Camera, Projector, and Related",
  "Equipment",
  "Movie Content Management",
  "Movie Sound Recording",
  "Movie Theatre",
  "See Film/Movie Theatre",
  "MTVs",
  "See Commercial Films and MTVs",
  "Music",
  "See Film and Music/Song",
  "See Film Music and Song",
  "Music and Song Composition",
  "Music/Song Composers and Song Lyric Writers",
  "Musical Films",
  "Multimedia",
  "See Film and Television, Internet, Multimedia",
  "Nan fang ji shi zhi fu shi guang ying = The Strait Story (2005)",
  "南方記事之浮世光影 (2005)",
  "Nationalism",
  "See Film, Nationalism, Nationality, Identity, and Localization",
  "Nationality",
  "See Film, Nationalism, Nationality, Identity, and Localization",
  "New Talents, Young Cinema Film Festival, 2004-",
  "Newspaper",
  "See Film and Newspaper/Journal",
  "Ni na bian ji dian = What Time Is It There? (2001)",
  "你那邊幾點? (2001)",
  "Opera",
  "See Film and Drama/Opera",
  "Opera/Drama Films",
  "The Opium War (1997)",
  "See Ya pian zhan zheng = The Opium War (1997)",
  "Others",
  "Film Artifacts",
  "Film Censorship",
  "Film Copyright, Piracy, and Intellectual Property",
  "Film Distribution",
  "Film Education",
  "Film Festivals and Awards",
  "Asia Pacific Film Festival, 1953-",
  "Golden Horse Film Festival and Awards, 1962-",
  "Golden Harvest Awards for Outstanding Short Films, 1978-",
  "Women Make Waves Film Festival, 1993-",
  "Taipei Film Festival, 1998-",
  "Taiwan International Documentary Festival, 1998-",
  "Taiwan International Ethnographic Film Festival, 2001-",
  "Taiwan International Animation Festival, 2003-",
  "New Talents, Young Cinema Film Festival, 2004-",
  "Film Industry",
  "Film Investment",
  "Film Law, Policy, Regulation, and Legal Case",
  "Film Market, Marketing, and Box Office",
  "Trailers",
  "Film Music and Song",
  "Film Posters",
  "Film Production and Management",
  "Digitization, Preservation, and Restoration",
  "Independent Film-Making",
  "Film Propaganda",
  "Film Screen Quota",
  "Film Still",
  "Film Subsidy",
  "Film Subtitle",
  "Film/Movie Theatre",
  "Ou, Wei, 1937-1973",
  "歐威, 1937-1973",
  "Qiu, Mingcheng (Chiu, Ming-chong), 1952-",
  "邱銘誠, 1952-",
  "Painting",
  "See Film and Painting",
  "Patients",
  "See Film and Patients",
  "The Peach Blossom Land (1992)",
  "See An lian Taohuayuan = The Peach Blossom Land (1992)",
  "The Peony Pavilion (1995)",
  "See Wo de mei li yu ai chou = The Peony Pavilion (1995)",
  "The Phoenix (1978)",
  "See Wu zi tian shu = The Phoenix (1978)",
  "Pingtung (Pingdong or P’ing-tung)",
  "See Kaohsiung (Gaoxiong) and Southern Taiwan, including Pingtung (Pingdong or P’ing-tung), Tainan (T’ai-nan), and Chiayi (Jiayi or Chia-i),1900-",
  "Po lun tai = Flat Tire (1998)",
  "破輪胎 (1998)",
  "Policy",
  "See Film Law, Policy, Regulation, and Legal Case",
  "Politics",
  "See Film and Politics",
  "Ponographic Films",
  "See “A”/Restricted/Ponographic Films",
  "Posters",
  "See Film Posters",
  "Postcolonial Theory",
  "Preservation",
  "See Digitization, Preservation, and Restoration",
  "Princess D (2002)",
  "See Xiang fei = Princess D (2002)",
  "Producers and Directors",
  "Production",
  "See Film Production and Management",
  "Projector",
  "See Movie Camera, Projector, and Related Equipment",
  "Propaganda",
  "See Film Propaganda",
  "Psychology",
  "See Film and Psychology",
  "The Puppetmaster (1995)",
  "See Xi meng ren sheng = The Puppetmaster (1995)",
  "Pushing Hands (1991)",
  "See Tui shou = Pushing Hands (1991)",
  "Qi mao qiu le = Fluffy Rhapsody (2000)",
  "起毛球了 (2000)",
  "Qian xi man bo = Millennium Mambo (2001)",
  "千禧曼波 (2001)",
  "Qiao ke li zhong ji = Chocolate Rap (2005)",
  "巧克力重擊 (2005)",
  "Qing shao nian Nezha = Rebels of the Neon God (1992)",
  "青少年哪吒 (1992)",
  "Qiongyao’s/Melodrama Films",
  "Qiu jue = Execution in Autumn (1972)",
  "秋決 (1972)",
  "Railway",
  "See Film and Railway",
  "Rebels of the Neon God (1992)",
  "See Qing shao nian Nezha = Rebels of the Neon God (1992)",
  "Reference materials:",
  "Bibliographies and Filmographies",
  "Indexes",
  "Dictionaries",
  "Directories",
  "Encyclopedias",
  "Catalogs, Guides, Handbooks, Factfinders, and Manuals\t\t\t\t\t\t0049-0069",
  "Regulation:",
  "See Film Law, Policy, Regulation, and Legal Case",
  "Religion",
  "See Film and Religion",
  "Ren yu Duoduo = The Shoe Fairy (2006)",
  "人魚朵朵 (2006)",
  "Restoration",
  "See Digitization, Preservation, and Restoration",
  "Restricted Films",
  "See “A”/Restricted/Ponographic Films",
  "The River (1997)",
  "See He liu = The River (1997)",
  "Saideke - Balai = Seediq  Bale (2011)",
  "賽德克 – 巴萊 (2011)",
  "San sheng you xing = Doubles / Giddens (2009)",
  "三生有幸 (2009)",
  "Science and Education Films",
  "Screenplay Writing",
  "Screenplays",
  "See film stories, Screenplays, AND SCRIPTS",
  "Screenwriters",
  "Scripts",
  "See film stories, Screenplays, AND SCRIPTS",
  "Se Jie = Lust, Caution (2007)",
  "色,戒 (2007)",
  "Seediq  Bale (2011)",
  "See Saideke - Balai = Seediq  Bale (2011)",
  "Set Design",
  "See Scenery and Set Design",
  "Sexuality",
  "See Film and Sexuality / Homosexuality",
  "Sha, Rongfeng, 1921-",
  "沙榮峰, 1921-",
  "The Shoe Fairy (2006)",
  "See Ren yu Duoduo = The Shoe Fairy (2006)",
  "Short Films",
  "Shuang tong = Double vision (2002)",
  "雙瞳 (2002)",
  "So Called Love (2008)",
  "See Ai de fa sheng lian xi = So Called Love (2008)",
  "Social Movement Documentary",
  "See 5.20 Incident, 1988 and Social Movement Documentary,1980s-1990s",
  "Society",
  "See Film and Sociology (Area/Audience/Family/City/Culture/Society)",
  "Sociology",
  "See Film and Sociology (Area/Audience/Family/City/Culture/Society)",
  "Song",
  "See Film and Music/Song",
  "See Film Music and Song",
  "Song Composers and Song Lyric Writers",
  "See Music/Song Composers and Song Lyric Writers",
  "Song Composition",
  "See Music and Song Composition",
  "Sound Recording",
  "See Movie Sound Recording",
  "Southern Taiwan",
  "See Kaohsiung (Gaoxiong) and Southern Taiwan ……",
  "Special Effects",
  "Specific film genres",
  "“A”/Restricted/Ponographic Films",
  "Animated Films",
  "Anti-Communist Films",
  "Art Films",
  "Children’s Films",
  "Comedy Films",
  "Commercial Films and MTVs",
  "Documentary Films",
  "Ethnographic Films",
  "Homosexual/Gay/Lesbian Films",
  "Horror and Ghost Films",
  "Independent Films",
  "Literary Films",
  "Martial Arts/Kung Fu Films",
  "Opera/Drama Films",
  "Musical Films",
  "Science and Education Films",
  "Short Films",
  "Teenage-Campus Films",
  "Qiongyao’s/Melodrama Films",
  "Special Regions, Periods, and Events",
  "Splendid Floart (2004)",
  "See Yan guang si she ge wu tuan = Splendid Floart (2004)",
  "Step By Step (2009)",
  "See Lian lian wu = Step By Step (2009)",
  "Still",
  "See Film Still",
  "Storm Over the Yang-Tse River (1969)",
  "See Yangzi jiang feng yun = Storm Over the Yang-Tse River (1969)",
  "The Strait Story (2005)",
  "See Nan fang ji shi zhi fu shi guang ying = The Strait Story (2005)",
  "Subsidy",
  "See Film Subsidy",
  "Subtitle",
  "See Film Subtitle",
  "Tai ying",
  "See Taiwan Provincial Film Production Studio ……",
  "Tai zhi",
  "See Taiwan Provincial Film Production Studio ……",
  "Taichung (Taizhong or T’ai-chung), 1910-",
  "Tainan (T’ai-nan)",
  "See Kaohsiung (Gaoxiong) and Southern Taiwan, including Pingtung (Pingdong or P’ing-tung), Tainan (T’ai-nan), and Chiayi (Jiayi or Chia-i), 1900-",
  "Taipei (Taibei), 1950-",
  "Taipei Film Festival, 1998-",
  "Taiwan and Bollywood Films",
  "Taiwan and Hollywood Films",
  "Taiwan and Hong Kong",
  "See Films in Taiwan, Hong Kong, and Mainland China",
  "Taiwan and Japan",
  "See Films in Taiwan and Japan",
  "Taiwan and Korea",
  "See Films in Taiwan and Korea",
  "Taiwan and Mainland China",
  "See Films in Taiwan, Hong Kong, and Mainland China",
  "Taiwan black movies (2005)",
  "See Taiwan hei dian ying = Taiwan black movies (2005)",
  "Taiwan Dian Ying Wen Hua Shi Ye Gu Fen You Xian Gong Si",
  "See Taiwan Provincial Film Production Studio ……",
  "Taiwan Dian Ying Wen Hua Xie Hui",
  "See Taiwan Film & Culture Association (Taiwan Dian Ying Wen Hua Xie Hui),  2001-",
  "Taiwan Dian Ying Zhi Pian Chang",
  "See Taiwan Provincial Film Production Studio ……",
  "Taiwan Film & Culture Association (Taiwan Dian Ying Wen Hua Xie Hui),  2001-",
  "Taiwan hei dian ying = Taiwan black movies (2005)",
  "台灣黑電影 (2005)",
  "Taiwan International Animation Festival, 2003-",
  "Taiwan International Documentary Festival, 1998-",
  "Taiwan International Ethnographic Film Festival, 2001-",
  "Taiwan New Cinema",
  "Taiwan New, New-New, and Post-New Cinema, 1982-",
  "Taiwan Provincial Film Production Studio (Taiwan sheng Dian Ying She Zhi Chang / Taiwan Sheng Zheng Fu Xin Wen Dian Ying Zhi Pian Chang / Taiwan Dian Ying Zhi Pian Chang / Taiwan Dian Ying Wen Hua Shi Ye Gu Fen You Xian Gong Si  / Tai ying or Tai zhi), 1945-1999",
  "Taiwan Sheng Dian Ying She Zhi Chang",
  "See Taiwan Provincial Film Production Studio ……",
  "Taiwan Sheng Zheng Fu Xin Wen Dian Ying Zhi Pian Chang",
  "See Taiwan Provincial Film Production Studio ……",
  "Taiwanese-dialect Film, 1955-1982",
  "Taizhong",
  "See Taichung (Taizhong or T’ai-chung), 1910-",
  "Tan, Fred",
  "See Dan, Hanzhang (Tan, Fred), 1949-1990",
  "Tang, Baoyun, 1944-1999",
  "唐寶雲, 1944-1999",
  "Tang shan guo Taiwan = The Heroic Pioneers (1986)",
  "唐山過台灣 (1986)",
  "Technology",
  "See Film and Technology",
  "Teenage-Campus Films",
  "Television",
  "See Film and Television, Internet, Multimedia",
  "Ten Worst Films Incident, 1977",
  "Terrorizers (1986)",
  "See Kong bu fen zi = Terrorizers (1986)",
  "Theatre",
  "See Film/Movie Theatre",
  "Three Times (2005)",
  "See Zui hao shi guang = Three Times (2005)",
  "Tian Sheng, Tian Hua Ying Ye Gong Si",
  "See Tiensheng & Tienhua Film Company (Tian Sheng, Tian Hua Ying Ye Gong Si), 1960-1978",
  "Tiensheng & Tienhua Film Company (Tian Sheng, Tian Hua Ying Ye Gong Si),",
  "The Tofu Maker Had a Dream (1994)",
  "See Wo de yi piao xuan zong tong = The Tofu Maker Had a Dream (1994)",
  "Tong, Yuejuan (Wan, Xiuying; Liang, Ruiying), 1914-",
  "童月娟 (萬秀英, 梁瑞英), 1914-",
  "A Touch of Zen (1969)",
  "See Xia nu = A Touch of Zen (1969)",
  "Toyojiro, Takamatsu, 1872-1952",
  "高松豐次郎, 1872-1952",
  "Trailers",
  "The Treasure Hunter (2009)",
  "See Ci Ling = The Treasure Hunter (2009)",
  "Tsai, Ming-liang",
  "See Cai, Mingliang (Tsai, Ming-liang), 1957-",
  "Tui shou = Pushing Hands (1991)",
  "推手 (1991)",
  "Union Film Co., Ltd. (Lian Bang Ying Ye You Xian Gong Si / Lian bang), 1953-1980",
  "Videotape",
  "See Film and Videotape",
  "Vive L’amour (1994)",
  "See Ai qing wan sui = Vive L’amour (1994)",
  "Le Voyage du Ballon Rouge (2006)",
  "See Hong qi qiu de lu xing = Flight of the Red Balloon = Le Voyage du Ballon Rouge (2006)",
  "Wan, Xiuying",
  "See Tong, Yuejuan (Wan, Xiuying; Liang, Ruiying), 1914-",
  "Wang, Feilin, 1956-1992.",
  "王菲林, 1956-1992.",
  "Wang, Shengshan, 1921-2003",
  "王生善, 1921-2003",
  "Wang, Tong (Wang, Tung) 1942-",
  "王童, 1942-",
  "Wang, Tung",
  "See Wang, Tong (Wang, Tung) 1942-",
  "Wang Xiang = Homesick Eyes (1997)",
  "望鄉 (1997)",
  "Wang, Xiaodi, 1953-",
  "王小棣, 1953-",
  "Wang, Zhengfang.",
  "王正方.",
  "The wedding banquet (1993)",
  "See Xi yan = The wedding banquet (1993)",
  "Wei, Desheng (Wei, Te-sheng), 1969-",
  "魏德聖, 1969-",
  "Wei, Ping’ao, 1929-1989",
  "魏平澳, 1929-1989",
  "Wei, Te-sheng",
  "See Wei, Desheng (Wei, Te-sheng), 1969-",
  "Weng, Dacheng, 1944-",
  "翁大成, 1944-",
  "What Time Is It There? (2001)",
  "See Ni na bian ji dian = What Time Is It There? (2001)",
  "Wind Within (1999)",
  "See Lu gang qing shen = Wind Within (1999)",
  "Wo de mei li yu ai chou = The Peony Pavilion (1995)",
  "我的美麗與哀愁 (1995)",
  "Wo de yi piao xuan zong tong = The Tofu Maker Had a Dream (1994)",
  "我的一票選總統 (1994)",
  "Wo hu cang long = Crouching Tiger, Hidden Dragon (2000)",
  "臥虎藏龍 (2000)",
  "Women",
  "See Film and Women",
  "Women Make Waves Film Festival, 1993-",
  "Wu, Mi-shen",
  "See Wu, Misen (Wu, Mi-sen) 1967-",
  "Wu, Misen (Wu, Mi-sen) 1967-",
  "吳米森, 1967-",
  "Wu, Nien-chen",
  "See Wu, Nianzhen (Wu, Nien-chen), 1952-",
  "Wu, Nianzhen (Wu, Nien-chen), 1952-",
  "吳念真1952-",
  "Wu yue zhi lian = Love of May (2004)",
  "五月之戀 (2004)",
  "Wu zi tian shu = The Phoenix (1978)",
  "無字天書 (1978)",
  "Xi bu lai de ren = The Man From West Island (1990)",
  "西部來的人 (1990)",
  "Xi meng ren sheng = The Puppetmaster (1995)",
  "戲夢人生 (1995)",
  "Xi yan = The wedding banquet (1993)",
  "囍宴 (2003)",
  "Xia nu = A Touch of Zen (1969)",
  "俠女 (1969)",
  "Xiang fei = Princess D (2002)",
  "想飛 (2002)",
  "Xiao, Juzhen (Hsiao, Chu-chen), 1972-",
  "蕭菊貞, 1972-",
  "Xiao zhen chun hui = Gain Sons, not Losing Daughters (1968)",
  "小鎮春回 (1968)",
  "Xiaoye, 1951-",
  "小野, 1951-",
  "Ximending (Ximenting), 1896-",
  "Ximenting",
  "See Ximending (Ximenting), 1896-",
  "Xin, Qi (Hsin, Chi), 1924-",
  "辛奇, 1924-",
  "Xinhua Film Corporation (Xinhua Ying Ye Gong Si), 1935-1984",
  "Xinhua Ying Ye Gong Si",
  "See Xinhua Film Corporation (Xinhua Ying Ye Gong Si), 1935-1984",
  "Xinzhu",
  "See Hsinchu (Xinzhu), 1900-",
  "Xu, Buliao (Pu-liao Hsu), 1951-1985",
  "許不了, 1951-1985",
  "Xu, Ligong (Hsu, Li-kong).",
  "徐立功.",
  "Ya pian zhan zheng = The Opium War (1997)",
  "鴉片戰爭 (1997)",
  "Yan guang si she ge wu tuan = Splendid Floart (2004)",
  "艷光四射歌舞團 (2004)",
  "Yang, Dechang (Yang, Edward), 1947-2007",
  "楊德昌, 1947-2007",
  "Yang, Edward",
  "See Yang, Dechang (Yang, Edward), 1947-2007",
  "Yang, Evan",
  "See Yi, Wen (Yang, Evan), 1920-1978",
  "Yang, Huishan, 1952-",
  "楊惠珊, 1952-",
  "Yang, Lihua, 1944-",
  "楊麗花, 1944-",
  "Yang, Shiqi",
  "楊士琪",
  "Yangzi jiang feng yun = Storm Over the Yang-Tse River (1969)",
  "揚子江風雲 (1969)",
  "Yao, Feng-pan",
  "See Yao, Fengpan (Yao, Feng-pan), 1932-2004",
  "Yao, Fengpan (Yao, Feng-pan), 1932-2004",
  "姚鳳磐, 1932-2004",
  "Yao, Yiwei, 1922-1997",
  "姚一葦, 1922-1997",
  "Yazhou Ying Ye Gong Si",
  "See Asia Film Corporation (Yazhou Ying Ye Gong Si), 1952-",
  "Yi ba jiu wu = The Legend of Formosa in 1895 (2008)",
  "一八九五 (2008)",
  "Yi qie wei le ming tian = Everything For the Events of Tomorrow (1988)",
  "一切為了明天 (1988)",
  "Yi, Wen (Yang, Evan), 1920-1978",
  "易文, 1920-1978",
  "Yin shi nan nu = Eat Drink Man Woman (1994)",
  "飲食男女 (1994)",
  "Ying lie qian qiu = The Everlasting Glory (1974)",
  "英烈千秋 (1974)",
  "Youth",
  "See Film and Youth",
  "Yuan, Congmei (Yuan, Tsung-mei), 1905-",
  "袁叢美, 1905-",
  "Yuan, Tsung-mei",
  "See Yuan, Congmei (Yuan, Tsung-mei), 1905-",
  "Zeng, Zhongying, 1924-",
  "曾仲影, 1924-",
  "Zhang, Che (Chang, Cheh), 1923-2002.",
  "張徹, 1923-2002.",
  "Zhang, Hongyi, 1950-2006",
  "張弘毅, 1950-2006",
  "Zhang, Meiyao, 1941-",
  "張美瑤, 1941-",
  "Zhou, Jielun (Chou, Jay), 1979-",
  "周傑倫, 1979-",
  "Zhang, Mingyu",
  "張明玉",
  "Zhang, Yi (Chang, Yi), 1951-",
  "張毅, 1951-",
  "Zhang, Ying, 1913-",
  "張英, 1913-",
  "Zhang, Zengze, 1930-",
  "張曾澤, 1930-",
  "Zhang, Zuoji (Chang, Tso-chi), 1961-",
  "張作驥, 1961-",
  "Zhao, Qibin, 1929-1986",
  "趙琦彬, 1929-1986",
  "Zheng, Wenhui (Cheng, Wun-hui), 1981-2007",
  "鄭文惠, 1981-2007",
  "Zhong Yang Dian Ying Shi Ye Gu Fen You Xian Gong Si / Zhong ying",
  "See Central Motion Picture Corporation (Zhong Yang Dian Ying Shi Ye Gu Fen You Xian Gong Si / Zhong ying), 1954-",
  "Zhongguo Dian Ying Zhi Pian Chang",
  "See China Motion Picture Studio (Zhongguo Dian Ying Zhi Pian Chang / Zhong zhi , 1933-  )",
  "Zhong ying",
  "See Central Motion Picture Corporation (Zhong Yang Dian Ying Shi Ye Gu Fen You Xian Gong Si / Zhong ying), 1954-",
  "Zhong zhi",
  "See China Motion Picture Studio (Zhongguo dian ying zhi pian chang / Zhong zhi) , 1933-",
  "Zhou, Meiling (Chou, Zoru), 1969-",
  "周美玲, 1969-",
  "Zhou, Tiansu (Chou, Tien-su), 1910-",
  "周天素, 1910-",
  "Zhu, Tianwen (Chu, T’ien-wen) , 1956-",
  "朱天文, 1956-",
  "Zui hao shi guang = Three Times (2005)",
  "最好時光 (2005)",
];
